### ISSUE TITLE
Can't access sheet with space in name

### ISSUE THREAD

**Issue by serialhex** [Voronchuk/elixir_google_spreadsheets#9]
When trying to access a spreadsheet using A2 notation, or using the `list_name:` argument the process dies and gives a metric crap-ton of output.

After some debugging, a solution: use `%20` instead of spaces.  I suggest the lib do this automatically (as my sheet is `test sheet` not `test%20sheet`).

**Comment by serialhex** [comment]
Found `URI` package, tried it, and reading works fine.  Writing breaks:

```
16:39:17.979 [error] GenServer #PID<0.415.0> terminating
** (stop) exited in: GenServer.call(#PID<0.448.0>, {:read_rows, 1, 21, [pad_empty: true, column_to: 5]}, 5000)
    ** (EXIT) an exception was raised:
        ** (WithClauseError) no with clause matching: {:ok, %HTTPoison.Response{body: "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum
-scale=1, width=device-width\">\n  <title>Error 400 (Bad Request)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px
}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22p
x;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.go
ogle.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/go
oglelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-web
kit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block
;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>400.</b> <ins>ThatΓÇÖs an error.</ins>\n  <p>Your client has issued a malformed
or illegal request.  <ins>ThatΓÇÖs all we know.</ins>\n", headers: [{"Content-Type", "text/html; charset=UTF-8"}, {"Referrer-Policy", "no-referrer"}, {"Content-Length", "1555"}, {"Date", "Fri, 15 Sep
2017 20:39:11 GMT"}], request_url: "https://sheets.googleapis.com/v4/spreadsheets/~~redacted~~/values:batchGet?majorDimension=ROWS&valueRenderOption=FORMATTED_VALUE&dat
eTimeRenderOption=FORMATTED_STRING&ranges=Sheet 1!A1:E1&ranges=Sheet 1!A2:E2&ranges=Sheet 1!A3:E3&ranges=Sheet 1!A4:E4&ranges=Sheet 1!A5:E5&ranges=Sheet 1!A6:E6&ranges=Sheet 1!A7:E7&ranges=Sheet 1!A8:
E8&ranges=Sheet 1!A9:E9&ranges=Sheet 1!A10:E10&ranges=Sheet 1!A11:E11&ranges=Sheet 1!A12:E12&ranges=Sheet 1!A13:E13&ranges=Sheet 1!A14:E14&ranges=Sheet 1!A15:E15&ranges=Sheet 1!A16:E16&ranges=Sheet 1!
A17:E17&ranges=Sheet 1!A18:E18&ranges=Sheet 1!A19:E19&ranges=Sheet 1!A20:E20&ranges=Sheet 1!A21:E21", status_code: 400}}
            (elixir_google_spreadsheets) lib/elixir_google_spreadsheets/spreadsheet.ex:465: GSS.Spreadsheet.spreadsheet_query_response/1
            (elixir_google_spreadsheets) lib/elixir_google_spreadsheets/spreadsheet.ex:352: GSS.Spreadsheet.handle_call/3
            (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.414.0>, {{{:with_clause, {:ok, %HTTPoison.Response{body: "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum
-scale=1, width=device-width\">\n  <title>Error 400 (Bad Request)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px
}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22p
x;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.go
ogle.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/go
oglelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-web
kit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block
;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>400.</b> <ins>ThatΓÇÖs an error.</ins>\n  <p>Your client has issued a malformed
or illegal request.  <ins>ThatΓÇÖs all we know.</ins>\n", headers: [{"Content-Type", "text/html; charset=UTF-8"}, {"Referrer-Policy", "no-referrer"}, {"Content-Length", "1555"}, {"Date", "Fri, 15 Sep
2017 20:39:11 GMT"}], request_url: "https://sheets.googleapis.com/v4/spreadsheets/~~redacted~~/values:batchGet?majorDimension=ROWS&valueRenderOption=FORMATTED_VALUE&dat
eTimeRenderOption=FORMATTED_STRING&ranges=Sheet 1!A1:E1&ranges=Sheet 1!A2:E2&ranges=Sheet 1!A3:E3&ranges=Sheet 1!A4:E4&ranges=Sheet 1!A5:E5&ranges=Sheet 1!A6:E6&ranges=Sheet 1!A7:E7&ranges=Sheet 1!A8:
E8&ranges=Sheet 1!A9:E9&ranges=Sheet 1!A10:E10&ranges=Sheet 1!A11:E11&ranges=Sheet 1!A12:E12&ranges=Sheet 1!A13:E13&ranges=Sheet 1!A14:E14&ranges=Sheet 1!A15:E15&ranges=Sheet 1!A16:E16&ranges=Sheet 1!
A17:E17&ranges=Sheet 1!A18:E18&ranges=Sheet 1!A19:E19&ranges=Sheet 1!A20:E20&ranges=Sheet 1!A21:E21", status_code: 400}}}, [{GSS.Spreadsheet, :spreadsheet_query_response, 1, [file: 'lib/elixir_google_
spreadsheets/spreadsheet.ex', line: 465]}, {GSS.Spreadsheet, :handle_call, 3, [file: 'lib/elixir_google_spreadsheets/spreadsheet.ex', line: 352]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server
.erl', line: 636]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 665]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, {GenServer, :call, [#PID<0.448.0>, {:read
_rows, 1, 21, [pad_empty: true, column_to: 5]}, 5000]}}}
State: %{port: #Port<0.10235>, worker_pid: #PID<0.414.0>}
```

thats some output for ya... This lib has made my life a lot easier, hopefully this can be fixed and made much nicer!! :smile_cat:

**Comment by Voronchuk** [comment]
Should be fine in #ba695f0, update to `0.1.8`
